---
title: Een uiterlijk kopiëren in Scratch 3
hero_image: images/banner.png
description: scratch3-uiterlijk-kopiëren beschrijving
version: 4
listed: false
copyedit: true
last_tested: "2019-08-23"
steps:
  - 
    title: Inleiding

