---
title: Scratch 3 मधील डुप्लिकेट costumes (पोशाख)
hero_image: images/banner.png
description: generic-scratch3-duplicate-costumes description
version: 4
listed: false
copyedit: true
last_tested: "2019-08-23"
steps:
  - title: परिचय

