---
title: Scratch 3でコスチュームを複製 (ふくせい) する
hero_image: images/banner.png
description: 一般的 (いっぱんてき) な Scratch 3 でのコスチューム複製の説明 (せつめい)
version: 4
listed: false
copyedit: true
last_tested: "2019-08-23"
steps:
  - 
    title: はじめに

