---
title: Duplicar fantasias no Scratch 3
hero_image: images/banner.png
description: descrição genérico-scratch3-duplicar-fantasias
version: 4
listed: false
copyedit: true
last_tested: "2019-08-23"
steps:
  - title: Introdução

