---
title: Duplicar disfraces en Scratch 3
hero_image: images / banner.png
description: descripción de duplicado-disfraces-generico-scratch3
version: 4
listed: false
copyedit: true
last_tested: "2019-08-23"
steps:
  - 
    title: Introducción

