---
title: مضاعفة المظاهر في برنامج سكراتش
hero_image: images/banner.png
description: وصف عام - scratch3 - مضاعفة- الكائنات
version: 4
listed: false
copyedit: true
last_tested: "2019-08-23"
steps:
  - title: المقدمة

