---
title: Duplicare un costume in Scratch 3
hero_image: images/banner.png
description: descrizione generic-scratch3-duplicate-costumes
version: 4
listed: false
copyedit: true
last_tested: "2019-08-23"
steps:
  - 
    title: Introduzione

